openapi: 3.0.0
info:
  title: Epic Movie Quotes API
  description: The space where users can share movies and quotes with each other.
  version: 1.0.0
servers:
  - url: http://localhost:8000/api
    description: local server
  - url: http://production-example:8000/api
    description: production server

components:
  securitySchemes:
    Auth:
      type: apiKey
      in: header
      name: Authorization
      description: Jwt
#  securitySchemes:
#    bearerAuth:
#      type: http
#      scheme: bearer
#      bearerFormat: JWT



paths:
  /login:
   $ref: "./_swagger/paths/auth.yaml#/paths/~1login"


  # /user:
  # $ref: "./_swagger/paths/auth.yaml#/paths/~1user"

  /movies:
    $ref: "./_swagger/paths/movies.yaml#/paths/~1movies"


#  /products/{id}:
#    $ref: "./_swagger/paths/products.yaml#/paths/~1products~1{id}"

  # /categories:
  # $ref: "./_swagger/paths/categories.yaml#/paths/~1categories"

#  schemas:
#    User:
#      allOf:
#        - $ref: "./_swagger/schemas/user.yaml#/components/schemas/User"
#    Product:
#      allOf:
#        - $ref: "./_swagger/schemas/product.yaml#/components/schemas/Product"
#    Category:
#      allOf:
#        - $ref: "./_swagger/schemas/category.yaml#/components/schemas/Category"
